#!/bin/tcsh

onintr cleanup
set Repeats = $argv[1]
shift

source shzzam_venv/bin/activate.csh >& /dev/null 
foreach TestFile ($argv)
    set ResultFile = "TestResults/`echo $TestFile | sed -e 's/TestFiles\///' -e 's#/#_#g'`"
    rm -f $ResultFile
    touch $ResultFile
    foreach Model (OpenAI Google)
        set Count = 1
        while ($Count <= $Repeats)
            @ Count++
            ShZZaM.py -q5 -M $Model -S OpenAI -p Vampire--- -m Vampire-SAT--- -v $TestFile | tee -a $ResultFile | grep 'RESULT:' | sed -e 's/RESULT: //' -e 's/\.\([A-Z][A-Z][A-Z]\)\.[^,]*/,\1/'
        end
    end
end
cleanup:
deactivate

